services:
  mongo:
    image: mongo:7
    container_name: mongo_spark_lab
    ports:
      - "27018:27017"          # локальний 27018 → контейнерний 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: